# Generated by Django 5.1.7 on 2025-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('PA', 'Pasaporte')], max_length=2)),
                ('num_identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cama', models.CharField(blank=True, choices=[('T/O', 'Terapia Ocupacional'), ('INF', 'Infantil'), ('CL2', 'Clínica Nivel 2'), ('CL1', 'Clínica Nivel 1'), ('ONC', 'Oncología'), ('NEU', 'Neurología'), ('UNEO', 'Unidad Neonatal'), ('CARD', 'Cardiología'), ('QUEM', 'Unidad de Quemados'), ('UCI', 'Unidad de Cuidados Intensivos'), ('HDD', 'Hospitalización Domiciliaria'), ('CIR', 'Cirugía'), ('EMER', 'Emergencias'), ('DIA', 'Diálisis'), ('OAMB', 'Otros Ambulatorios')], max_length=10, null=True)),
                ('cuarentena', models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Aislamiento de gotas', 'Aislamiento de gotas'), ('Aislamiento por aire', 'Aislamiento por aire'), ('Aislamiento protector', 'Aislamiento protector'), ('Código Púrpura', 'Código Púrpura'), ('Viruela del mono', 'Viruela del mono')], max_length=30, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
