# Generated by Django 5.1.7 on 2025-03-31 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250330_1524'),
    ]

    operations = [
    ]
