# Generated by Django 5.1.7 on 2025-03-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250330_2001'),
    ]

    operations = [
    ]
