# Generated by Django 5.1.7 on 2025-04-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dieta'),
    ]

    operations = [
    ]
