# Generated by Django 5.1.7 on 2025-04-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250401_1651'),
    ]

    operations = [
    ]
