# Generated by Django 5.1.7 on 2025-04-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20250401_1719'),
    ]

    operations = [
    ]
