# Generated by Django 5.1.7 on 2025-04-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250401_1722'),
    ]

    operations = [
    ]
