# Generated by Django 5.1.7 on 2025-04-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250401_1751'),
    ]

    operations = [
    ]
