# Generated by Django 5.1.7 on 2025-04-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250401_1813'),
    ]

    operations = [
    ]
