# Generated by Django 5.1.7 on 2025-04-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250401_2000'),
    ]

    operations = [
    ]
