# Generated by Django 5.1.7 on 2025-04-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20250401_2009'),
    ]

    operations = [
    ]
