# Generated by Django 5.1.7 on 2025-04-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20250401_2012'),
    ]

    operations = [
    ]
