# Generated by Django 5.1.7 on 2025-04-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20250402_1010'),
    ]

    operations = [
    ]
