# Generated by Django 5.1.7 on 2025-04-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20250402_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='indicadores_dieta',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='medidas',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='nombre_d_b',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='periodos',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='tipo_biberon',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='tipo_dieta',
        ),
        migrations.AlterField(
            model_name='dieta',
            name='acompanante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DetalleDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dieta', models.CharField(choices=[('Dieta', 'Dieta'), ('Biberones', 'Biberones')], max_length=10)),
                ('descripcion_dieta', models.CharField(max_length=100)),
                ('medidas', models.CharField(choices=[('Unidad', 'Unidad'), ('Onzas', 'Onzas')], max_length=20)),
                ('medidas_cantidad', models.PositiveIntegerField()),
                ('periodos', models.CharField(choices=[('D', 'D'), ('CM', 'CM'), ('A', 'A'), ('CV', 'CV'), ('M', 'M'), ('TODOS', 'TODOS')], max_length=10)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='accounts.dieta')),
            ],
        ),
    ]
