# Generated by Django 5.1.7 on 2025-04-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_dieta_indicadores_dieta_remove_dieta_medidas_and_more'),
    ]

    operations = [
    ]
