# Generated by Django 5.1.7 on 2025-04-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20250402_1105'),
    ]

    operations = [
    ]
