# Generated by Django 5.1.7 on 2025-04-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20250402_1250'),
    ]

    operations = [
    ]
