# Generated by Django 5.1.7 on 2025-04-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20250402_1440'),
    ]

    operations = [
    ]
