# Generated by Django 5.1.7 on 2025-04-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20250402_1849'),
    ]

    operations = [
    ]
