# Generated by Django 5.1.7 on 2025-04-03 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20250402_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F1', models.CharField(blank=True, max_length=20, null=True)),
                ('F2', models.CharField(blank=True, max_length=20, null=True)),
                ('F3', models.CharField(blank=True, max_length=20, null=True)),
                ('F4', models.CharField(blank=True, max_length=20, null=True)),
                ('F5', models.CharField(blank=True, max_length=20, null=True)),
                ('F6', models.CharField(blank=True, max_length=20, null=True)),
                ('F7', models.CharField(blank=True, max_length=20, null=True)),
                ('F8', models.CharField(blank=True, max_length=20, null=True)),
                ('F9', models.CharField(blank=True, max_length=20, null=True)),
                ('F10', models.CharField(blank=True, max_length=20, null=True)),
                ('F11', models.CharField(blank=True, max_length=20, null=True)),
                ('F12', models.CharField(blank=True, max_length=20, null=True)),
                ('F13', models.CharField(blank=True, max_length=20, null=True)),
                ('F14', models.CharField(blank=True, max_length=20, null=True)),
                ('F15', models.CharField(blank=True, max_length=20, null=True)),
                ('F16', models.CharField(blank=True, max_length=20, null=True)),
                ('F17', models.CharField(blank=True, max_length=20, null=True)),
                ('F18', models.CharField(blank=True, max_length=20, null=True)),
                ('F19', models.CharField(blank=True, max_length=20, null=True)),
                ('F20', models.CharField(blank=True, max_length=20, null=True)),
                ('F21', models.CharField(blank=True, max_length=20, null=True)),
                ('F22', models.CharField(blank=True, max_length=20, null=True)),
                ('F23', models.CharField(blank=True, max_length=20, null=True)),
                ('F24', models.CharField(blank=True, max_length=20, null=True)),
                ('detalle_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frecuencias', to='accounts.detalledieta')),
            ],
        ),
    ]
