# Generated by Django 5.1.7 on 2025-04-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_frecuencia'),
    ]

    operations = [
    ]
