# Generated by Django 5.1.7 on 2025-04-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20250402_1948'),
    ]

    operations = [
    ]
