# Generated by Django 5.1.7 on 2025-04-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20250403_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frecuencia',
            name='F1',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F10',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F11',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F12',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F13',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F14',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F15',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F16',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F17',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F18',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F19',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F2',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F20',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F21',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F22',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F23',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F24',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F3',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F4',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F5',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F6',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F7',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F8',
        ),
        migrations.RemoveField(
            model_name='frecuencia',
            name='F9',
        ),
        migrations.AddField(
            model_name='frecuencia',
            name='tipo_frecuencia',
            field=models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10'), ('F11', 'F11'), ('F12', 'F12'), ('F13', 'F13'), ('F14', 'F14'), ('F15', 'F15'), ('F16', 'F16'), ('F17', 'F17'), ('F18', 'F18'), ('F19', 'F19'), ('F20', 'F20'), ('F21', 'F21'), ('F22', 'F22'), ('F23', 'F23'), ('F24', 'F24')], default='F1', max_length=3),
            preserve_default=False,
        ),
    ]
