# Generated by Django 5.1.7 on 2025-04-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_frecuencia_f1_remove_frecuencia_f10_and_more'),
    ]

    operations = [
    ]
