# Generated by Django 5.1.7 on 2025-04-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20250404_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledieta',
            name='descripcion_biberon',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Leche Entera', 'Leche Entera'), ('Agua Estéril', 'Agua Estéril'), ('Formula 75', 'Formula 75'), ('Formula Maternizada', 'Formula Maternizada'), ('Enteral Artesanal isocalórica', 'Enteral Artesanal isocalórica (1 KCAL/ML)'), ('Enteral Artesanal Hipercalórica-Hiperproteica', 'Enteral Artesanal Hipercalórica-Hiperproteica (1,5 KCAL/ML)'), ('Jugo', 'Jugo'), ('Papilla', 'Papilla'), ('Cereal en Agua', 'Cereal en Agua'), ('Cereal en Leche', 'Cereal en Leche'), ('Formula 100', 'Formula 100'), ('Suplementos Alimenticios', 'Suplementos Alimenticios'), ('Enteral Artesanal Hipercalórica-Normoproteica', 'Enteral Artesanal Hipercalórica-Normoproteica (1,2 KCAL/ML)'), ('Yogurt', 'Yogurt'), ('Infusión de Ciruela', 'Infusión de Ciruela'), ('Litros de Agua', 'Litros de Agua')], default='Ninguno', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detalledieta',
            name='descripcion_dieta',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('General', 'General'), ('Hipocalórica', 'Hipocalórica'), ('Blanda Mecánica', 'Blanda Mecánica'), ('Liquida Amplia', 'Liquida Amplia'), ('Cetogenica', 'Cetogenica'), ('Alta en Fibra', 'Alta en Fibra'), ('Blanda Astringente', 'Blanda Astringente'), ('Hipercalórica', 'Hipercalórica'), ('Diabético', 'Diabético'), ('Hiperproteica', 'Hiperproteica'), ('Hiposódica', 'Hiposódica'), ('Complementaria', 'Complementaria'), ('Liquida Estricta', 'Liquida Estricta'), ('Tratamiento Dialítico', 'Tratamiento Dialítico'), ('Blanda Neutropénica', 'Blanda Neutropénica'), ('Blanda Hipograsa', 'Blanda Hipograsa')], default='Ninguno', max_length=100, null=True),
        ),
    ]
