# Generated by Django 5.1.7 on 2025-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_detalledieta_descripcion_biberon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledieta',
            name='periodos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
