# Generated by Django 5.1.7 on 2025-04-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_detalledieta_periodos'),
    ]

    operations = [
    ]
