# Generated by Django 5.1.7 on 2025-04-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_detalledieta_descripcion_biberon_and_more'),
    ]

    operations = [
    ]
