# Generated by Django 5.1.7 on 2025-04-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20250404_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledieta',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Frecuencia',
        ),
    ]
