# Generated by Django 5.1.7 on 2025-04-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_detalledieta_frecuencia_delete_frecuencia'),
    ]

    operations = [
    ]
