# Generated by Django 5.1.7 on 2025-04-06 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20250404_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='fecha_actual',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
