# Generated by Django 5.1.7 on 2025-04-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_datospersonales_fecha_actual'),
    ]

    operations = [
    ]
