# Generated by Django 5.1.7 on 2025-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20250406_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='indicaciones',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='restricciones',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
