# Generated by Django 5.1.7 on 2025-04-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_dieta_indicaciones_dieta_restricciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledieta',
            name='descripcion_dieta',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Madre Lactante', 'Madre Lactante'), ('Familiar', 'Familiar'), ('General', 'General'), ('Hipocalórica', 'Hipocalórica'), ('Blanda Mecánica', 'Blanda Mecánica'), ('Liquida Amplia', 'Liquida Amplia'), ('Cetogenica', 'Cetogenica'), ('Alta en Fibra', 'Alta en Fibra'), ('Blanda Astringente', 'Blanda Astringente'), ('Hipercalórica', 'Hipercalórica'), ('Diabético', 'Diabético'), ('Hiperproteica', 'Hiperproteica'), ('Hiposódica', 'Hiposódica'), ('Complementaria', 'Complementaria'), ('Liquida Estricta', 'Liquida Estricta'), ('Tratamiento Dialítico', 'Tratamiento Dialítico'), ('Blanda Neutropénica', 'Blanda Neutropénica'), ('Blanda Hipograsa', 'Blanda Hipograsa')], default='Ninguno', max_length=100, null=True),
        ),
    ]
