# Generated by Django 5.1.7 on 2025-04-08 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_detalledieta_descripcion_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledieta',
            name='fecha_det_dieta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
