# Generated by Django 5.1.7 on 2025-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20250408_1748'),
    ]

    operations = [
    ]
