# Generated by Django 5.1.7 on 2025-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20250409_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_actual',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='detalledieta',
            name='fecha_det_dieta',
            field=models.DateField(),
        ),
    ]
