# Generated by Django 5.1.7 on 2025-04-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_datospersonales_fecha_actual_and_more'),
    ]

    operations = [
    ]
