# Generated by Django 5.1.7 on 2025-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20250409_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='indicaciones',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='restricciones',
        ),
        migrations.AddField(
            model_name='detalledieta',
            name='indicaciones',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalledieta',
            name='restricciones',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
