# Generated by Django 5.1.7 on 2025-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_detalledieta_descripcion_biberon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledieta',
            name='fecha_det_dieta',
            field=models.DateField(verbose_name='Fecha del Detalle'),
        ),
    ]
